### ISSUE TITLE
Is this package still alive?

### ISSUE THREAD

**Issue by jasonxeno** [Tarang/Meteor-Analytics#21]
When I go to: https://tail.sh/getting_started
Couldn't find a template named "GettingStarted" or "gettingStarted". Are you sure you defined it?

**Comment by Tarang** [comment]
Yes still alive. Its a one person team!

I've not given it much love lately but i have a couple of updates to put up.

I fixed the getting started page. Iron router was converting our names (https://github.com/iron-meteor/iron-router/issues/484). We did an update to fix it but an upgrade to iron router undid our changes (we used a fork)
