### ISSUE TITLE
Should analytics:analytics be unmigrated?

### ISSUE THREAD

**Issue by dandv** [Tarang/Meteor-Analytics#26]
I understand from [the blog](https://tail.sh/blog) that https://atmospherejs.com/analytics/analytics was the original package name, but you've renamed it to tail:core so that ad blockers don't block it. Maybe worth running `meteor admin set-unmigrated analytics:analytics` now?

**Comment by Tarang** [comment]
@dandv We use both. `tail:core` is just for those users who use adblock :)

**Comment by dandv** [comment]
Right. What I'm suggesting is simply *hiding* `analytics:analytics` from Atmosphere searches (but letting the package be installable by existing apps). Is there a good reason for anyone to prefer analytics:analytics over tail:core? Seems they're identical, just with a different name.

**Comment by Tarang** [comment]
The name is a bit easier to remember. Ideally i'd prefer `analytics:analytics` over `tail:core` its just i have to get a way past adblock (during development). Its not an issue in production. I think i've found a way to do it.

I'm working on an update to tail at the moment as we also have to sort out the ability to take on more signups too.
